//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pluralsight_challenge.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pluralsight_challenge.Tests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question|answer|distractors
        ///What is 1754 - 3936?|-2182|3176, 6529, 6903
        ///What is 3009 * 5075?|15270675|3572, 8772, 9415
        ///What is 9702 - 9102?|600|7360, 2043, 2982, 1235
        ///What is 6324 * 4040?|25548960|3952, 3906, 2694
        ///What is 7269 * 2771?|20142399|874
        ///What is 4354 - 5398?|-1044|3253
        ///What is 1129 - 7801?|-6672|5432, 7846, 239
        ///What is 163 - 7924?|-7761|4603
        ///What is 2075 - 6504?|-4429|1579
        ///What is 4749 + 7170?|11919|2825, 1994, 8839, 9094
        ///What is 4352 + 8781?|13133|6305, 2714, 2763
        ///What is 2125 + 5741? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string code_challenge_question_dump {
            get {
                return ResourceManager.GetString("code_challenge_question_dump", resourceCulture);
            }
        }
    }
}
